[package]
name = "icedb-issues"
version = "0.0.0"
edition = "2021"

[dependencies]
once_cell = "1.2"
regex = "1"
reqwest = { version = "0.11", features = ["blocking", "json"] }
serde = "1"
serde_json = "1"
